# Generated by Django 3.1.7 on 2021-02-19 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FarmersApp', '0002_auto_20210219_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_size', models.DecimalField(decimal_places=6, max_digits=9)),
                ('farm_size_units', models.CharField(choices=[('1', 'Acres'), ('2', 'Hectares'), ('3', 'Meter Squared')], max_length=20)),
                ('crop_grown', models.CharField(max_length=40)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('farm_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm', to='FarmersApp.farmer')),
            ],
        ),
    ]
