# Generated by Django 3.1.7 on 2021-02-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmsApp', '0004_auto_20210219_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='farm_size_units',
            field=models.CharField(choices=[('Acres', 'Acres'), ('Hectares', 'Hectares'), ('Meter Squared', 'Meter Squared')], default='Acres', max_length=20),
        ),
    ]
