# Generated by Django 3.1.7 on 2021-02-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmsApp', '0005_auto_20210219_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='farm_size',
            field=models.FloatField(),
        ),
    ]
