# Generated by Django 3.1.7 on 2021-02-19 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FarmsApp', '0006_auto_20210219_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='farm_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farm',
            name='modified_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='farm_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
