# Generated by Django 3.1.7 on 2021-02-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmsApp', '0007_auto_20210219_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='crop_grown',
            field=models.CharField(choices=[('Maize', 'Maize'), ('Beans', 'Beans'), ('Kales', 'Kales')], default='Maize', max_length=20),
        ),
    ]
