# Generated by Django 3.1.7 on 2021-02-23 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FarmsApp', '0008_auto_20210223_1116'),
        ('FarmsApp', '0008_auto_20210223_1048'),
    ]

    operations = [
    ]
