# Generated by Django 3.1.7 on 2021-02-19 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HarvestsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvestphotos',
            name='belongs_to',
        ),
        migrations.AddField(
            model_name='harvest',
            name='photos',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='harvest_photo', to='HarvestsApp.harvestphotos'),
        ),
    ]
