# Generated by Django 3.1.7 on 2021-02-19 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HarvestsApp', '0002_auto_20210219_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvest',
            name='photos',
        ),
        migrations.AddField(
            model_name='harvestphotos',
            name='belongs_to',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='harvest_photo', to='HarvestsApp.harvest'),
        ),
    ]
