# Generated by Django 3.1.7 on 2021-02-19 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flagged_item_reason', models.CharField(max_length=30)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='item_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='item_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
