# Generated by Django 3.1.7 on 2021-02-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FlaggedItemsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flaggeditems',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='flaggeditems',
            name='modified_by',
        ),
    ]
